FROM justworld/init_ubuntu:18.04

ENV LANG C.UTF-8

RUN mkdir -p /var/web/django_app1 \
    && cd /var/web/django_app1/

WORKDIR /var/web/django_app1/

EXPOSE 8077

COPY requirements.txt /var/web/django_app1/requirements.txt

RUN pip install -r requirements.txt -i https://pypi.douban.com/simple

COPY / /var/web/django_app1/

ENTRYPOINT ["python", "manage_dev.py", "runserver", "0:8077"]