FROM justworld/init_ubuntu:18.04

RUN mkdir -p /var/web/django_app1

COPY / /var/web/django_app1/

WORKDIR /var/web/django_app1/

RUN cd /var/web/django_app1/ \
 && apt install -y python3 \
 && apt clean \
 && pip install -r requirements.txt -i https://pypi.douban.com/simple

EXPOSE 8077

ENTRYPOINT ["python", "manage_dev.py", "runserver", "0:8077"]
